const books = [
  {
    author: "Dan Brown",
    books: [
      {
        id: "1",
        article: "1",
        title: "Inferno",
        description: "Далеко-далеко за словесными горами в стране.",
        age: "16+",
        author: "Dan Brown",
        img: "images/dan brown inferno.jpg",
        price: 15,
        isAddedToCart: false,
      },
      {
        id: "2",
        article: "2",
        title: "The Lost Symbol",
        description: "Далеко-далеко за словесными горами в стране.",
        age: "16+",
        author: "Dan Brown",
        img: "images/dan brown The Lost Symbol.jpg",
        price: 25,
        isAddedToCart: false,
      },
      {
        id: "3",
        article: "3",
        title: "Da vinci code",
        description: "Далеко-далеко за словесными горами в стране.",
        age: "16+",
        author: "Dan Brown",
        img: "images/dan brown da vinci code.jpg",
        price: 20,
        isAddedToCart: false,
      },
      {
        id: "4",
        article: "4",
        title: "Digital Fortress",
        description: "Далеко-далеко за словесными горами в стране.",
        age: "16+",
        author: "Dan Brown",
        img: "images/dan brown digital fortress.jpg",
        price: 35,
        isAddedToCart: false,
      },
      {
        id: "5",
        article: "5",
        title: "Deception Point",
        description: "Далеко-далеко за словесными горами в стране.",
        age: "16+",
        author: "Dan Brown",
        img: "images/dan brown Deception Point.jpg",
        price: 27,
        isAddedToCart: false,
      },
      {
        id: "6",
        article: "6",
        title: "Angels and Demons",
        description: "Далеко-далеко за словесными горами в стране.",
        age: "16+",
        author: "Dan Brown",
        img: "images/dan brown angels and demons.jpg",
        price: 31,
        isAddedToCart: false,
      },
    ],
  },
  {
    author: "George Oruell",
    books: [
      {
        id: "7",
        article: "7",
        title: "1984",
        description: "Далеко-далеко за словесными горами в стране.",
        age: "16+",
        author: "George Oruell",
        img: "images/george oruell 1984.jpg",
        price: 42,
        isAddedToCart: false,
      },
    ],
  },
  {
    author: "Oldos Hecksley",
    books: [
      {
        id: "8",
        article: "8",
        title: "Brawe New World",
        description: "Далеко-далеко за словесными горами в стране.",
        age: "16+",
        author: "Oldos Hecksley",
        img: "images/oldos hecksley bnw.jpg",
        price: 45,
        isAddedToCart: false,
      },
    ],
  },
  {
    author: "Michael Bulgakov",
    books: [
      {
        id: "9",
        article: "9",
        title: "Master and Margarett",
        description: "Далеко-далеко за словесными горами в стране.",
        age: "16+",
        author: "Michael Bulgakov",
        img: "images/bulgakovmm.jpg",
        price: 38,
        isAddedToCart: false,
      },
    ],
  },
];

export default books;
